### ISSUE TITLE
where's the definition of 'num_updates'

### ISSUE THREAD

**Issue by Laputa142857** [AhmedFrikha/ARCADe-A-Rapid-Continual-Anomaly-Detector#1]
In the file 'arcade_main.py',line 333,the definition of the parameter 'num_updates'can't be found.

**Comment by AhmedFrikha** [comment]
num_updates comes from the JSON configuration file.  An exemplary configuration file was provided for each of the 3 datasets.

For example for omniglot you should run:
python arcade_main.py -config_file=config_OMN_ARCADe_H_BN_K10_seq10.json
